services:
  - type: web
    name: ecomzone-web
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
        healthCheckPath: /health
    healthCheckInterval: 60
    disk:
      name: uploads
      mountPath: /opt/render/project/public/uploads
      sizeGB: 10
